name: steam_auth
description: Port of a C# library to work with Steam Mobile Authenticator
version: 0.0.1
homepage:

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  crypto: ^3.0.2
  flutter:
    sdk: flutter
  requests: ^4.3.0
  pointycastle: ^3.6.0
  uuid: ^3.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
