name: steam_auth
description: Port of a C# library to work with Steam Mobile Authenticator
version: 1.0.3
homepage: https://github.com/Prevter/SteamAuthDart
repository: https://github.com/Prevter/SteamAuthDart

environment:
  sdk: ">=2.17.0 <3.0.0"

dependencies:
  crypto: ^3.0.2
  pointycastle: ^3.6.0
  uuid: ^3.0.6
  dio: ^4.0.6
  dio_cookie_manager: ^2.0.0
  cookie_jar: ^3.0.0

dev_dependencies:
  lints: ^1.0.0
  test: ^1.16.0
